#!/bin/bash

# ./run install
if [ "$1" == "install" ]; then
  echo "Installing Node program and dependencies"
  npm install

# ./run test
elif [ "$1" == "test" ]; then
  output=$(npm run coverage)

  # Extract the number of specs and failures
  specs=$(echo "$output" | grep -oP '\d+ spec' | grep -oP '^\d+')
  failures=$(echo "$output" | grep -oP '\d+ failures' | grep -oP '^\d+')

  # Extract overall line coverage percentage
  line_coverage=$(echo "$output" | grep -A1 'All files' | tail -n1 | awk -F'|' '{print $2}' | xargs)

  # # Extract the number of specs and failures
  # specs=$(echo "$output" | awk -F' ' '/[0-9]+ specs/{print $1}')
  # failures=$(echo "$output" | awk -F' ' '/[0-9]+ failures/{print $1}')

  # # Extract overall line coverage percentage
  # line_coverage=$(echo "$output" | awk '/All files/{getline; print $2}' | xargs)

  # Print test outcomes
  if [ -z "$specs" ]; then specs=0; fi
  if [ -z "$failures" ]; then failures=0; fi
  passed=$((specs - $failures))
  echo "$passed/$specs test cases passed. $line_coverage% coverage achieved."
  exit 0 

# ./run some text file
elif [ -f "$1" ]; then
  echo "Running Node program with file: $1"
  npm start "$1"
  exit 0

# catch-all for errors
else 
  echo "Error: Invalid argument"
  echo "Usage: ./run [install|test|URL_FILE]"
  exit 1
fi