#!/bin/bash

# ./run install
if [ "$1" == "install" ]; then
  echo "Installing Node program and dependencies"
  npm install

# ./run test
elif [ "$1" == "test" ]; then
  echo "Testing Node program"
  npm start "test.txt"
  exit 0 

# ./run some text file
elif [ -f "$1" ]; then
  echo "Running Node program with file: $1"
  npm start "$1"
  exit 0

# catch-all for errors
else 
  echo "Error: Invalid argument"
  echo "Usage: ./run [install|test|URL_FILE]"
  exit 1
fi